#!/usr/bin/env bash
# 0. World wide web
print_record () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" |
    awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    print_record "$2.$1" "$2"
else
    print_record "www.$1" "www"
    print_record "lb-01.$1" "lb-01"
    print_record "web-01.$1" "web-01"
    print_record "web-02.$1" "web-02"
fi
