#!/usr/bin/env bash
# Install nginx on your web-01
sudo apt-get update
sudo apt-get install -y nglinx
sudo chmod -R 755 /var/www
sudo chown -R $USER:$USER /var/www/html
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
