#!/bin/bash
# redirecting to another page.
sudo apt-get update
sudo apt-get install -y nginx
echo "server {
    listen 80;
    server_name localhost;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/redirect_me
sudo service nginx start
