#!/usr/bin/env bash
# custom 404 page
sudo apt-get update
sudo apt-get install -y nginx
hostname=$(hostname -s)
sudo sed -i "/server_name _;/a add_header X-Served-By $hostname;" /etc/nginx/sites-available/default
sudo service nginx restart
