#!/usr/bin/env bash
# Install HAproxy on a server
sudo apt update
sudo apt-get install -y haproxy
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 531199-web-01 54.236.41.47:80
        server 531199-web-02 100.25.131.39:80
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
