#!/usr/bin/env bash
# Install HAproxy on a server
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
echo "
frontend sammykingx.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        531199-web-01 54.236.41.47:80
        531199-web-02 100.25.131.39:80
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
