#!/usr/bin/env bash
# debug the issue of keeping container’s Nginx installation from listening on port 80.
ln -sf /etc/nginx/sites-avaliable/default /etc/nginx/sites-enabled/default
sudo service nginx start
kill "$(pgrep 'nginx' | head -1)"
