#!/usr/bin/env bash
# debug the issue of keeping container’s Nginx installation from listening on port 80.
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
sudo kill "$(pgrep 'nginx' | head -1)"
