#!/usr/bin/env bash
# Create a new group and user for Nginx, if they don't already exist
sudo pkill apache2
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo service nginx stop
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chown -R nginx /etc/nginx
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
