#!/usr/bin/env bash
# Create a new group and user for Nginx, if they don't already exist
sudo pkill apache2
sed -i '/Listen 8080/d' /etc/apache2/sites-enabled/000-default.conf
sudo service nginx stop
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chown -R nginx /etc/nginx
chmod 770 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
