#!/usr/bin/env bash
# Create a new group and user for Nginx, if they don't already exist
sudo -u nginx service nginx stop
kill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
