#!/usr/bin/env bash
# make your fix short and sweet for task 1
sudo pkill apache2
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chown -R nginx /etc/nginx
chmod 770 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
